### ISSUE TITLE
How to use user input VCF file?

### ISSUE THREAD

**Issue by yudizhangzyd** [lvclark/polyRAD#13]
Hi there,

I had an error when I was trying to call VCF2RADdata, the command is:
VCF2RADdata(myVCF, possiblePloidies = list(c(2,2)), expectedLoci = 100, expectedAlleles = 500)
the error is:
"Error in VCF2RADdata(myVCF, possiblePloidies = list(c(2, 2)), expectedLoci = 100,  : 
  Need to adjust min.ind.with.reads for number of samples in dataset."

Could you please tell me how to fix this?
Besides, does your method work for one single individual? Thanks.

Best,
Yudi

**Comment by lvclark** [comment]
polyRAD won't work on a single individual, since it needs information from a population (ideally hundreds) in order to estimate priors for genotyping.

You need to set `min.ind.with.reads` to a value that is the number of individuals in your dataset or lower.

You also probably want much higher values for `expectedLoci` and `expectedAlleles`.  As stated in the tutorial, the values were only set that low because a dummy dataset was being imported.
