### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by relshire** [lvclark/polyRAD#40]
Thank you for developing this software. It meets a big need in the genomics world. I am keen to use it myself for GBS data. I was the lead developer of that method in the Buckler lab at Cornell.

As part of my volunteer work ([Genomics for Aotearoa New Zealand](https://genomics.nz) charitable society), I am packaging this up into a docker container. We include a bunch of relevant metadata (e.g. publication doi, source code url, documentation url, etc.). One component is the license under which the software is released.  I was unable to find a license for polyRAD. Would you please add one?

This [site](https://spdx.org/licenses/) has a bunch of licenses, perhaps too many to consider. If it were my decision, I would use the GNU Affero GPL v3.0 or later, or one of the BSD licenses.

Thanks for considering this request!

**Comment by lvclark** [comment]
Hi Rob,

Thanks for making the Docker container, and many many thanks for developing GBS!  We did a lot of really productive work in _Miscanthus_ with that genotyping method.

polyRAD has a GPL >= 2.0 license.  Following R package convention, this is listed in the DESCRIPTION file rather than having a separate LICENSE file.

Best,

Lindsay

**Comment by relshire** [comment]
Hi Lindsay,

Many thanks for the explanation of the R package convention. That'll be useful in the future as well.

Best,

Rob
